services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - app
    networks:
      - default
  app:
    restart: always
    init: true
    image: seriyyy95/feedbackie-app:fpm-latest
    volumes:
      - ./:/var/www
      - ./data/app:/data
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_KEY=${APP_KEY:-changeme}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@feedbackie.app}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_USERNAME=${DB_USERNAME:-}
      - DB_CONNECTION=${DB_CONNECTION:-sqlite}
      - MAIL_USER=${SMTP_USER:-}
      - MAIL_HOST=${SMTP_HOST:-}
      - MAIL_PORT=${SMTP_PORT:-}
      - MAIL_PASSWORD=${SMTP_PASSWORD:-}
    networks:
      - default
networks:
    default:
